//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_Newspaper.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.Guesses = new HashSet<Guess>();
            this.Newspapers = new HashSet<Newspaper>();
        }
    
        public string Admin_usernane { get; set; }
        [DataType(DataType.Password)]
        public string Admin_password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Admin_password" , ErrorMessage = "Mật khẩu không khớp với mật khẩu ở trên")]
        public string Admin_repassword { get; set; }

        public int Admin_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guess> Guesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Newspaper> Newspapers { get; set; }
    }
}
