//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_Newspaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liked
    {
        public int LikedId { get; set; }
        public Nullable<int> Guess_id { get; set; }
    
        public virtual Guess Guess { get; set; }
    }
}
