//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_Newspaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newspaper
    {
        public int Id_bao { get; set; }
        public byte[] Anh { get; set; }
        public string NoiDung { get; set; }
        public string TieuDe { get; set; }
        public int Admin_id { get; set; }
        public int Id_chuyenmuc { get; set; }
        public string TieuDePhu { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ChuyenMuc ChuyenMuc { get; set; }
    }
}
