//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_Newspaper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewspaperDboV3Entities : DbContext
    {
        public NewspaperDboV3Entities()
            : base("name=NewspaperDboV3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ChuyenMuc> ChuyenMucs { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Guess> Guesses { get; set; }
        public virtual DbSet<Liked> Likeds { get; set; }
        public virtual DbSet<Newspaper> Newspapers { get; set; }
    }
}
